USE [master]
GO

/****** Object:  Database [BridgepayDB]    Script Date: 03/03/2023 07:27:03 a. m. ******/
CREATE DATABASE [BridgepayDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BridgepayDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BridgepayDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BridgepayDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BridgepayDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BridgepayDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BridgepayDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BridgepayDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BridgepayDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BridgepayDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BridgepayDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BridgepayDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BridgepayDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BridgepayDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BridgepayDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BridgepayDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BridgepayDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BridgepayDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BridgepayDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BridgepayDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BridgepayDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BridgepayDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BridgepayDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BridgepayDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BridgepayDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BridgepayDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BridgepayDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BridgepayDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BridgepayDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BridgepayDB] SET  MULTI_USER 
GO

ALTER DATABASE [BridgepayDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BridgepayDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BridgepayDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BridgepayDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BridgepayDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BridgepayDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BridgepayDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [BridgepayDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [BridgepayDB] SET  READ_WRITE 
GO


